name: "Build + Coverage"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: "33 5 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        ros_distribution: [ rolling ]
        include:
          - docker_image: ubuntu:jammy
            ros_distribution: rolling
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.3.0
      with:
        use-ros2-testing: true
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - name : Download and install dependencies
      run: |
        apt-get install ros-${{ matrix.ros_distribution }}-rclc
    - uses : ros-tooling/action-ros-ci@0.2.4
      with:
        package-name: "micro_ros_diagnostic_msgs micro_ros_diagnostic_updater micro_ros_common_diagnostics"
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-defaults: |
          {
            "build": {
              "mixin": ["coverage-gcc", "coverage-pytest"]
            },
            "test": {
              "mixin": ["coverage-pytest"]
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    - uses: codecov/codecov-action@v1.5.0
      with:
        file: ros_ws/lcov/total_coverage.info
